<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenSynapse.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenSynapse.Core\OpenSynapse.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenSynapse.App" />
    <InternalsVisibleTo Include="OpenSynapse.Core.Tests" />
    <InternalsVisibleTo Include="OpenSynapse.HardwareValidation" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Devices\Manifests\*.json" />
  </ItemGroup>
</Project>
